name: Tests

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.5        
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add(PackageSpec(name="MongocUtils",rev="main")); Pkg.instantiate()'
      - name: Run Tests
        run: julia -e 'include("/home/runner/work/MongocUtils.jl/MongocUtils.jl/test/runtests.jl")'
        
    
